name: better_self
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.2.0
  get: ^4.6.6
  hive_ce: 2.5.0+2
  hive_ce_flutter: 2.0.0
  hive_ui: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/mindful.png
    - assets/dailyroutine.png
    - assets/gratefulness.png
    - assets/largescreen.png
    - assets/plan.png
    - assets/priorities.png
    - assets/progress_ls.png
    - assets/progress.png
    - assets/routines_detailed.png
    - assets/routines.png
    - assets/start.png

